# Generated by Django 2.1.2 on 2018-10-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_type',
            field=models.CharField(choices=[('BL', 'Bronze Legacy'), ('GL', 'Gold Legacy'), ('CO', 'Continuous'), ('CU', 'Current Until'), ('IL', 'Installment Life'), ('LM', 'Life Member'), ('NM', 'New Member'), ('UP', 'Unpaid')], max_length=20),
        ),
    ]
