# Generated by Django 2.1.2 on 2018-10-18 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_auto_20181016_0206'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_by_post', models.BooleanField()),
                ('paid_by_post_date', models.DateField()),
                ('emailed', models.BooleanField()),
                ('card_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.Member')),
            ],
        ),
    ]
